mcmd import -p sys_md_Package.tsv
mcmd import -p personal_lookup_gender_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_genotypicsex_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_countryofresidence_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_ethnicity_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_countryofbirth_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_inclusionstatus_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_primaryaffiliatedinstitute_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_dataavailableinotherinstitutes_attributes.tsv --as attributes --in fair-genomes
mcmd import -p informedconsentform_lookup_consentformcreator_attributes.tsv --as attributes --in fair-genomes
mcmd import -p informedconsentform_lookup_consentformrestrictedto_attributes.tsv --as attributes --in fair-genomes
mcmd import -p individualconsent_lookup_restrictedto_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_gender.tsv --as fair-genomes_personal_lookup_gender --in fair-genomes
mcmd import -p personal_lookup_genotypicsex.tsv --as fair-genomes_personal_lookup_genotypicsex --in fair-genomes
mcmd import -p personal_lookup_countryofresidence.tsv --as fair-genomes_personal_lookup_countryofresidence --in fair-genomes
mcmd import -p personal_lookup_ethnicity.tsv --as fair-genomes_personal_lookup_ethnicity --in fair-genomes
mcmd import -p personal_lookup_countryofbirth.tsv --as fair-genomes_personal_lookup_countryofbirth --in fair-genomes
mcmd import -p personal_lookup_inclusionstatus.tsv --as fair-genomes_personal_lookup_inclusionstatus --in fair-genomes
mcmd import -p personal_lookup_primaryaffiliatedinstitute.tsv --as fair-genomes_personal_lookup_primaryaffiliatedinstitute --in fair-genomes
mcmd import -p personal_lookup_dataavailableinotherinstitutes.tsv --as fair-genomes_personal_lookup_dataavailableinotherinstitutes --in fair-genomes
mcmd import -p informedconsentform_lookup_consentformcreator.tsv --as fair-genomes_informedconsentform_lookup_consentformcreator --in fair-genomes
mcmd import -p informedconsentform_lookup_consentformrestrictedto.tsv --as fair-genomes_informedconsentform_lookup_consentformrestrictedto --in fair-genomes
mcmd import -p individualconsent_lookup_restrictedto.tsv --as fair-genomes_individualconsent_lookup_restrictedto --in fair-genomes
