mcmd import -p sys_md_Package.tsv
mcmd import -p personal_lookup_gender_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_genotypicsex_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_countryofresidence_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_ethnicity_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_countryofbirth_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_inclusionstatus_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_primaryaffiliatedinstitute_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_dataavailableinotherinstitutes_attributes.tsv --as attributes --in fair-genomes
mcmd import -p informedconsentform_lookup_consentformcreator_attributes.tsv --as attributes --in fair-genomes
mcmd import -p informedconsentform_lookup_consentformrestrictedto_attributes.tsv --as attributes --in fair-genomes
mcmd import -p individualconsent_lookup_restrictedto_attributes.tsv --as attributes --in fair-genomes
mcmd import -p material_lookup_materialtype_attributes.tsv --as attributes --in fair-genomes
mcmd import -p material_lookup_anatomicalsource_attributes.tsv --as attributes --in fair-genomes
mcmd import -p material_lookup_storageconditions_attributes.tsv --as attributes --in fair-genomes
mcmd import -p samplepreparation_lookup_librarypreparationkit_attributes.tsv --as attributes --in fair-genomes
mcmd import -p samplepreparation_lookup_targetenrichmentkit_attributes.tsv --as attributes --in fair-genomes
mcmd import -p sequencing_lookup_sequencingplatform_attributes.tsv --as attributes --in fair-genomes
mcmd import -p sequencing_lookup_sequencinginstrumentmodel_attributes.tsv --as attributes --in fair-genomes
mcmd import -p sequencing_lookup_sequencingtype_attributes.tsv --as attributes --in fair-genomes
mcmd import -p analysis_lookup_physicaldatalocation_attributes.tsv --as attributes --in fair-genomes
mcmd import -p personal_lookup_gender.tsv --as fair-genomes_personal_lookup_gender --in fair-genomes
mcmd import -p personal_lookup_genotypicsex.tsv --as fair-genomes_personal_lookup_genotypicsex --in fair-genomes
mcmd import -p personal_lookup_countryofresidence.tsv --as fair-genomes_personal_lookup_countryofresidence --in fair-genomes
mcmd import -p personal_lookup_ethnicity.tsv --as fair-genomes_personal_lookup_ethnicity --in fair-genomes
mcmd import -p personal_lookup_countryofbirth.tsv --as fair-genomes_personal_lookup_countryofbirth --in fair-genomes
mcmd import -p personal_lookup_inclusionstatus.tsv --as fair-genomes_personal_lookup_inclusionstatus --in fair-genomes
mcmd import -p personal_lookup_primaryaffiliatedinstitute.tsv --as fair-genomes_personal_lookup_primaryaffiliatedinstitute --in fair-genomes
mcmd import -p personal_lookup_dataavailableinotherinstitutes.tsv --as fair-genomes_personal_lookup_dataavailableinotherinstitutes --in fair-genomes
mcmd import -p informedconsentform_lookup_consentformcreator.tsv --as fair-genomes_informedconsentform_lookup_consentformcreator --in fair-genomes
mcmd import -p informedconsentform_lookup_consentformrestrictedto.tsv --as fair-genomes_informedconsentform_lookup_consentformrestrictedto --in fair-genomes
mcmd import -p individualconsent_lookup_restrictedto.tsv --as fair-genomes_individualconsent_lookup_restrictedto --in fair-genomes
mcmd import -p material_lookup_materialtype.tsv --as fair-genomes_material_lookup_materialtype --in fair-genomes
mcmd import -p material_lookup_anatomicalsource.tsv --as fair-genomes_material_lookup_anatomicalsource --in fair-genomes
mcmd import -p material_lookup_storageconditions.tsv --as fair-genomes_material_lookup_storageconditions --in fair-genomes
mcmd import -p samplepreparation_lookup_librarypreparationkit.tsv --as fair-genomes_samplepreparation_lookup_librarypreparationkit --in fair-genomes
mcmd import -p samplepreparation_lookup_targetenrichmentkit.tsv --as fair-genomes_samplepreparation_lookup_targetenrichmentkit --in fair-genomes
mcmd import -p sequencing_lookup_sequencingplatform.tsv --as fair-genomes_sequencing_lookup_sequencingplatform --in fair-genomes
mcmd import -p sequencing_lookup_sequencinginstrumentmodel.tsv --as fair-genomes_sequencing_lookup_sequencinginstrumentmodel --in fair-genomes
mcmd import -p sequencing_lookup_sequencingtype.tsv --as fair-genomes_sequencing_lookup_sequencingtype --in fair-genomes
mcmd import -p analysis_lookup_physicaldatalocation.tsv --as fair-genomes_analysis_lookup_physicaldatalocation --in fair-genomes
